name: Publish

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      docker_tag_prefix:
        description: "Enter the Docker Tag Prefix (e.g adhoc-test)"
        required: true
        type: string
env:
  REGISTRY: ghcr.io
  DOCKER_TAG_PREFIX: ${{ github.event.inputs.docker_tag_prefix }}

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
      - name: 🏷️ Generate Tag and Image Name
        run: |
          BRANCH_OR_TAG=$(basename ${{ github.ref }})
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            PREFIX=${{ env.DOCKER_TAG_PREFIX }}
            SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            echo "TAG=$PREFIX-$BRANCH_OR_TAG-$SHORT_SHA" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ] && [ -n "${{ github.event.ref }}" ]; then
            echo "TAG=$BRANCH_OR_TAG" >> $GITHUB_ENV
          else
            echo "Invalid event. Exiting..."
            exit 1
          fi
          # Convert repository name to lowercase for container registry
          echo "IMAGE_NAME_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: 🔑 Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 🔍 Check if Tag already exists
        id: checktag
        run: |
          TAG_EXISTS=$(docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.TAG }} > /dev/null 2>&1 && echo "found" || echo "not found")
          echo "tag=$TAG_EXISTS" >> $GITHUB_OUTPUT
          if [ "$TAG_EXISTS" = "found" ]; then
            echo "::warning::Tag ${{ env.TAG }} already exists in the registry. Skipping build and push."
          else
            echo "Tag ${{ env.TAG }} does not exist. Proceeding with build and push."
          fi
      - name: 🛠️ Build and Push Docker Image
        if: steps.checktag.outputs.tag == 'not found'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.TAG }}
          labels: |
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.description=Mina Delegation Program Coordinator and Validator Component
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.version=${{ env.TAG }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
      - name: ❌ Tag Already Exists
        if: steps.checktag.outputs.tag == 'found'
        run: |
          echo "::error::Tag ${{ env.TAG }} already exists in ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}"
          echo "Please use a different tag name or delete the existing image."
          exit 1
